# Generated by Django 4.1.5 on 2023-02-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='number_dni',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
